services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: fundoo-sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Pass123
    ports:
      - "1433:1433"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: fundoo-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:7-alpine
    container_name: fundoo-redis
    ports:
      - "6379:6379"

  userservice:
    environment:
    - ASPNETCORE_URLS=http://+:8080
    - ConnectionStrings__UserDb=Server=sqlserver;Database=FundooUsersDb;User Id=sa;Password=YourStrong@Pass123;TrustServerCertificate=True;
    build:
      context: .
      dockerfile: src/Services/UserService/Fundoo.UserService.API/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
      - rabbitmq

  notesservice:
    environment:
    - ASPNETCORE_URLS=http://+:8080
    build:
      context: .
      dockerfile: src/Services/NotesService/Fundoo.NotesService.API/Dockerfile
    ports:
      - "5002:8080"
    depends_on:
      - sqlserver
      - redis
      - rabbitmq

  apigateway:
    build:
      context: .
      dockerfile: src/ApiGateway/Fundoo.ApiGateway/Dockerfile
    ports:
      - "7000:8080"
    depends_on:
      - userservice
      - notesservice